service: sample-service

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10

functions:
  doit:
    handler: sample.doit
    events:
      - http:
          path: /foo
          method: post
          integration: lambda

